"""SEC data access, filing selection, and Company Facts retrieval."""

from .client import SECClient, SECClientError, SECRequestError, SECResponseError
from .company_facts import (
    CompanyFactsDataError,
    SECCompanyFacts,
    SECFactConcept,
    SECFactObservation,
    SECFactValue,
    fetch_company_facts,
)
from .filing_selection import (
    FilingSelectionError,
    SelectedFilings,
    load_and_select_filings,
    select_filings,
)
from .filing_xbrl import (
    FilingXBRLContext,
    FilingXBRLDataError,
    FilingXBRLDimension,
    FilingXBRLError,
    FilingXBRLFact,
    FilingXBRLQName,
    FilingXBRLSourceError,
    FilingXBRLUnit,
    SECExtractedXBRLArtifact,
    SECFilingXBRL,
    discover_extracted_xbrl,
    fetch_filing_xbrl,
    parse_filing_xbrl_instance,
)
from .fact_selection import (
    FactSelectionError,
    FilingFactObservations,
    ObservationPeriodType,
    ObservationRelationship,
    SelectedFactObservation,
    SelectedFactObservations,
    select_fact_observations,
)
from .submissions import (
    SECFiling,
    SECSubmissionHistoryFile,
    SECSubmissions,
    SubmissionsDataError,
    fetch_submission_history,
    fetch_submissions,
)
from .tickers import (
    SECCompanyIdentity,
    TickerDataError,
    TickerNotFoundError,
    TickerResolutionError,
    resolve_ticker,
)

__all__ = [
    "CompanyFactsDataError",
    "FactSelectionError",
    "FilingSelectionError",
    "FilingFactObservations",
    "FilingXBRLContext",
    "FilingXBRLDataError",
    "FilingXBRLDimension",
    "FilingXBRLError",
    "FilingXBRLFact",
    "FilingXBRLQName",
    "FilingXBRLSourceError",
    "FilingXBRLUnit",
    "ObservationPeriodType",
    "ObservationRelationship",
    "SECClient",
    "SECClientError",
    "SECCompanyFacts",
    "SECCompanyIdentity",
    "SECExtractedXBRLArtifact",
    "SECFactConcept",
    "SECFactObservation",
    "SECFactValue",
    "SECFiling",
    "SECFilingXBRL",
    "SECSubmissionHistoryFile",
    "SECRequestError",
    "SECResponseError",
    "SECSubmissions",
    "SelectedFilings",
    "SelectedFactObservation",
    "SelectedFactObservations",
    "SubmissionsDataError",
    "TickerDataError",
    "TickerNotFoundError",
    "TickerResolutionError",
    "fetch_company_facts",
    "discover_extracted_xbrl",
    "fetch_filing_xbrl",
    "fetch_submission_history",
    "fetch_submissions",
    "load_and_select_filings",
    "parse_filing_xbrl_instance",
    "resolve_ticker",
    "select_fact_observations",
    "select_filings",
]
